version: '3.4'
services:
  indicator-service:
    image: indicador-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /indicator-service
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
